### PR TITLE
Default behavior for pcbdraw without subcommand

### PR DESCRIPTION
**Pull request by set-soft**
- This makes the command line compatible with v0.9.0

### CODE REVIEW

**Comment by yaqwsx** [comment]
I don't like this change. There is a reason why we released a new major version - to allow for breaking changes. The goal was to get a clearer UI. Having the fallback for being compatible is directly against the spirit of changes, and also, this change brings so much boilerplate code.

**Comment by set-soft** [comment]
I understand the idea of a major number change.
But I don't understand why you don't want to maintain it compatible, you just need to add a small source file (nothing compared with the nightmare of dependencies pcbdraw pulls) and do a few changes in the click interface, very small ones. That's all, with this *all* scripts using pcbdraw remains unchanged.

**Comment by yaqwsx** [comment]
The goal is that the users to notice what all PcbDraw can do and also to clearly communicate that the intended usage has changed. Why should the plot command be preferred over, e.g., render? Once we get sufficient API in KiCAD, the render command might be actually preferred by most users. Plot command isn't superior in any way. "It used to be other way" isn't an argument for me. It doesn't mean it was good. If I wanted to maintain backward compatibility, I could have made 0.10 release.

Regarding dependencies: I perceive a difference between a third-party dependency (that is maintained by someone else) and code in a codebase.

If the users want to stick to the old UI, they can continue using v0.9. Or write a wrapper script.

**Comment by set-soft** [comment]
> Why should the plot command be preferred over, e.g., render?

Because this is what 99% of users do?
Anyways, I see we have very different points of view. I'll look for another solutions.

**Comment by yaqwsx** [comment]
I care more about idiomatic usage (which requires the command to be always present) than having short circuits that can be (in my opinion) confusing. I also guess that once we have proper support for rendering, 95% of the users would actually prefer to render than plot (I have no real numbers, it is just a guess). What do we in that case? Introduce another breaking change? Or are we stuck with the unpreferred way of using the tool? 

This change also doesn't ensure backwards compatibility (e.g., we now specify side explicitly instead of `--back`).  And, again, I find it more idiomatic to specify `--side=back` than a switch `--back` that isn't really clear (and also, misses the `--front` counterpart). This is why a major release release was introduced.

**Pull request closed without merging**
