### PR TITLE
Render backside

### PR DESCRIPTION
**Pull request by wifasoi**
This PR will allow to render the backside of the board (issue #4 ).
I added the mirror feature as-well.

keep it up with the good work! :+1:

### CODE REVIEW

**Comment by wifasoi** [comment]
ok, having a file for the bottom view of THT components is not so bad .. I'll try to implement in the following days.

**Comment by yaqwsx** [comment]
I like it! I think the warning are completely ok and the library should always provide the bottom view (even it is empty). 

I have one last thing I would like to discuss with you; in the quick proposal I suggested to use the word "back" to distinguish the sides. However now I am thinking "bottom" would be more suitable as it is consistent with PCB layers naming. What do you think?

**Comment by wifasoi** [comment]
The "clever" hack i did  works even when the component is mounted on the backside of the board...(e.g. pin headers) so using the "bottom" postfix can cause confusion (I think).
I don't want to bikeshedding much on this, but maybe "CompBottom" or similar is better.
Your project, your call (https://i.imgur.com/aUbk9ha.gifv)

**Comment by yaqwsx** [comment]
You are right - bottom has strong association with a fixed side of a board. However for the components it is a relative point of view.

So let's keep it with "back".

Thank you for the contribution!

**Pull request merged**
