### PR TITLE
Various patches in order to make the examples usable.

### PR DESCRIPTION
**Pull request by set-soft**
I know this patch is violent, but I was trying to run the examples and found a lot of problems.
I understand you recently did important changes and the repo became inconsistent.
The patch adds some coherence to the docs and examples.
It also adds the hability to run the scipts without installing. This isn't very "pythonic", but is much more easy to clone the repo and start using (assuming dependencies are met).

- No need for libmagickwand-dev and other tools
- Hability to run the scripts without installing
- Populate is now part of PcbDraw
- ./populate and ./pcbdraw won't work.
- Merged examples/pcbdraw/examples.md with examples/readme.md
- Fixed paths in examples
- Added support for default libs to populate.py
- Fixed populate always generating SVGs

### CODE REVIEW

**Comment by yaqwsx** [comment]
Thank you for your contribution. The documentation is indeed out-of-date and I appreciate your work and I am happy to merge the documentation. 

I have some proposal for your changes to the code:
- I dislike having a global name `here`
- why is it necessary to append anything to `sys.path`?
- `generate_image` was rewritten so it supports various image formats, so your patch probably needs an adjustment.

Could you make changes to your PR? On top of this, I prefer when you PR consists of 2 commits - one for the documentation, the second one for the code. Both of them should have descriptive names (see https://chris.beams.io/posts/git-commit/)

Then I will be happy to merge your PR.

**Comment by set-soft** [comment]
Hi!

> why is it necessary to append anything to sys.path?

To allow running the scripts without installing it.
I see you did some overlapping changes, let me review the patches.

**Comment by set-soft** [comment]
I merged all your changes to my fork, one by one to cleanly solves conflicts.
The main conflict was related to the way you implement "builtin" styles.
IMHO is a very uncommon mechanism, I already was implementing something similar but different.
Lets say you want to specify the *builtin* `oshpark-purple.json` style, you just use:

```
--style oshpark-purple
```

Now lets say you want to use a file you created, and you chose (in a strike of bad ideas ;-) to name it just like the *builtin*, you use:

```
--style oshpark-purple.json
```

If you are crazy enough to don't use the .json extension it will look ambiguous, but the code will actually load your file and not the builtin.

Additionally I added support for system level configuration files in `/usr/share/pcbdraw/styles/`.

For this I use:

```
def find_data_file(name, ext, subdir):
    if os.path.isfile(name):
        return name
    # Not a file here, needs extension?
    ln = len(ext)
    if name[-ln:] != ext:
        name += ext
        if os.path.isfile(name):
            return name
    # With the sources?
    local_name = os.path.join(PKG_BASE, subdir, name)
    if os.path.isfile(local_name):
        return local_name
    # System level?
    global_name = os.path.join(GLOBAL_DATA_DIR, subdir, name)
    if os.path.isfile(global_name):
        return global_name
    raise RuntimeError("Missing '" + subdir + "' " + name)
```

I'll try to do a PR.

**Comment by set-soft** [comment]
I separated all the code patches and some patches I had and made individual PRs.
When they are merged I'll separate the docs stuff.

**Comment by yaqwsx** [comment]
The other patches were merged. Could you create a separate PR for the documentation? Could you also include the changes in search paths?

**Comment by set-soft** [comment]
I recycled this PR.
Added the explanation about the search path.
Also added a --help epilog containing the actual search path.
BTW: you can close #35 and #34

**Pull request merged**
