### PR TITLE
Fix #117 and Improvement on unit.read_resistance

### LINKED ISSUE #117: "ValueError: Cannot parse '470' to resistance" (populate)
Hello,
I'm trying to use the res_band feature with populate.
I get this error:

Traceback (most recent call last):
  File "/home/david/.local/bin/pcbdraw", line 8, in <module>
    sys.exit(run())
  File "/home/david/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/david/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/david/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/david/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/david/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/david/.local/lib/python3.8/site-packages/pcbdraw/populate.py", line 300, in populate
    parsed_content = generate_images(parsed_content, board, prepare_params(header["params"]),
  File "/home/david/.local/lib/python3.8/site-packages/pcbdraw/populate.py", line 193, in generate_images
    generate_image(boardfilename, x["side"], x["components"],
  File "/home/david/.local/lib/python3.8/site-packages/pcbdraw/populate.py", line 212, in generate_image
    plot.main(args=plot_args)
  File "/home/david/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/david/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/david/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/david/.local/lib/python3.8/site-packages/pcbdraw/ui.py", line 174, in plot
    image = plotter.plot()
  File "/home/david/.local/lib/python3.8/site-packages/pcbdraw/plot.py", line 1053, in plot
    plotter.render(self)
  File "/home/david/.local/lib/python3.8/site-packages/pcbdraw/plot.py", line 812, in render
    plotter.walk_components(invert_side=False, callback=self._append_component)
  File "/home/david/.local/lib/python3.8/site-packages/pcbdraw/plot.py", line 1084, in walk_components
    callback(lib, name, ref, value, pos)
  File "/home/david/.local/lib/python3.8/site-packages/pcbdraw/plot.py", line 840, in _append_component
    ret = self._create_component(lib, name, ref, value)
  File "/home/david/.local/lib/python3.8/site-packages/pcbdraw/plot.py", line 890, in _create_component
    self._apply_resistor_code(component_element, id_prefix, ref, value)
  File "/home/david/.local/lib/python3.8/site-packages/pcbdraw/plot.py", line 912, in _apply_resistor_code
    res, tolerance = self._get_resistance_from_value(value)
  File "/home/david/.local/lib/python3.8/site-packages/pcbdraw/plot.py", line 947, in _get_resistance_from_value
    res = read_resistance(value_l[0])
  File "/home/david/.local/lib/python3.8/site-packages/pcbdraw/unit.py", line 39, in read_resistance
    raise ValueError(f"Cannot parse '{value}' to resistance")
ValueError: Cannot parse '470' to resistance

If I understand correctly, the value '470' is retrieved from the .kicad_pcb file.
The script parses correctly an other value (100k) and generates correctly the corresponding picture.

Also, in this case I use the default resistor footprint. Not my custom one (see other issue #116 )

Thank you.

### PR DESCRIPTION
**Pull request by Electro707**
This PR fixes the issue raised in #117 where `unit.read_resistance` does not handle non-unit numbers.

I also took the opportunity to improve the function. Because the code calling this function expects a `decimal.InvalidOperation` if it cannot parse a number, the `read_resistance` function now attempts to parse a number and if it's unable to, it will return `InvalidOperation` which is handled by the calling function. Previously it will also return a `ValueError` which isn't handled in the calling code.

### CODE REVIEW

**Comment by yaqwsx** [comment]
Thank you for the fix. The function didn't accept values without any marking on purpose - all the schematics that I have ever worked with never used raw numbers to mark the resistance. Therefore, a raw number was considered an error that should be reported to the user.

However, as I understood from the recent bug reports, there are actually users using raw numbers as resistance marking. So I guess it makes sense to allow them, and there is no harm in doing so.

However, I don't like the change in error handling this PR introduces. The `ValueError` was thrown whenever we weren't able to parse the number correctly (consistently with what Python built-ins `int` and `float` do). The exception also has a human-readable description. No other exception was ever thrown. 

The changes you introduce change this behavior; multiple types of exceptions can be thrown, and, also most of them contain error messages that cannot be understood outside of the function as they will contain partial values extracted from the input string.

There is, however, one mistake. The exception is not immediately thrown on purpose; it should be cought by the top-level caller and reported in a user-readable way. This is currently missing in the implementation of [`plot`](https://github.com/yaqwsx/PcbDraw/blob/d717719eeaa50df65b13bc827e688543d8182b79/pcbdraw/ui.py#L127)

**Comment by Electro707** [comment]
Ah, in that case a 'try-except' block should be to the `_get_resistance_from_value` in `plot.py` to handle `ValueError`s. I can address that with this PR after reverting the exception changes I made

**Comment by yaqwsx** [comment]
The Decimal error handling in `_get_resistance_from_value` is just a relict of the past that hasn't been addressed once we switched away from the `engineering_notation` library.

**Comment by Electro707** [comment]
In commit f4e53b2, I also fixed a bug when the `resistor-flip` option is given. As this PR is related to the resistor color band feature, I figured to add it to this PR instead of creating another PR just for that fix.

**Comment by Electro707** [comment]
@yaqwsx The build failed, but I noticed there is a bug in commit 148aede7922b20f88c4662fac38aec09f91bcc6c (the resistance value test) where 
` assert read_resistance("4700k") == D("47000000") `
is has an extra zero in the assertion check

**Comment by yaqwsx** [comment]
You can run the tests locally via `make test-unit` You don't have to wait for the CI.

**Comment by Electro707** [comment]
Fixed the issue and the test passes (checked it locally, but wanted it on Github's end as well)

**Comment by Electro707** [comment]
It looks like the commit fixing the resistor flip option is gone. I can't see it in the commit logs after I rebased.
I'm guessing that I pushed that commit from my desktop, and forgot to pull it before rebasing to master.

**Comment by yaqwsx** [comment]
Hi, any update on this?

**Comment by Electro707** [comment]
Yes, as I've stated this PR no longer includes the flipping fix due to accidentally doing a rebase on my laptop without that commit pulled. This PR looks good to be merged imo

**Comment by yaqwsx** [comment]
Before doing so, could you squash the commit into a single one with meaningful commit message as I requested?

**Comment by Electro707** [comment]
Oh, I mis-read the "two commits" as two PRs. Done

**Pull request merged**
